<?php

namespace ContainerX3t6Odr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VV2udfNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vV2udfN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vV2udfN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'TodolistRepository' => ['privates', 'App\\Repository\\TodolistRepository', 'getTodolistRepositoryService', true],
            'serializer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
            'validatorInterface' => ['services', '.container.private.validator', 'get_Container_Private_ValidatorService', false],
        ], [
            'TodolistRepository' => 'App\\Repository\\TodolistRepository',
            'serializer' => '?',
            'validatorInterface' => '?',
        ]);
    }
}
