<?php

namespace ContainerX3t6Odr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XYLkTaPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xYLkTaP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xYLkTaP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'validatorInterface' => ['services', '.container.private.validator', 'get_Container_Private_ValidatorService', false],
        ], [
            'userRepository' => 'App\\Repository\\UserRepository',
            'validatorInterface' => '?',
        ]);
    }
}
