<?php

namespace ContainerX3t6Odr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTodolistServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\TodolistService' shared autowired service.
     *
     * @return \App\Services\TodolistService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/TodolistService.php';

        return $container->privates['App\\Services\\TodolistService'] = new \App\Services\TodolistService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
