<?php

namespace ContainerPig7lcS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1XliZaFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1XliZaF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1XliZaF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'userRepository' => ['privates', '.errored.vybDxpY', NULL, 'Cannot determine controller argument for "App\\Controller\\UserController::index()": the $userRepository argument is type-hinted with the non-existent class or interface: "App\\Entity\\UserRepository".'],
        ], [
            'userRepository' => '?',
        ]);
    }
}
