<?php

namespace ContainerPig7lcS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_VybDxpYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.vybDxpY' shared service.
     *
     * @return \App\Entity\UserRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\UserController::index()": the $userRepository argument is type-hinted with the non-existent class or interface: "App\\Entity\\UserRepository".');
    }
}
