<?php

namespace ContainerXDQiAyx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getToDoListService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.aJ7VWpY.App\Entity\ToDoList' shared service.
     *
     * @return \App\Entity\ToDoList
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.aJ7VWpY": it references class "App\\Entity\\ToDoList" but no such service exists.');
    }
}
