<?php

namespace ContainerH7Z1CLj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LdgHOc4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LdgHOc4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LdgHOc4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'itemRepository' => ['privates', 'App\\Repository\\ItemRepository', 'getItemRepositoryService', true],
            'serializer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
            'validatorInterface' => ['services', '.container.private.validator', 'get_Container_Private_ValidatorService', false],
        ], [
            'itemRepository' => 'App\\Repository\\ItemRepository',
            'serializer' => '?',
            'validatorInterface' => '?',
        ]);
    }
}
