<?php

namespace Container2v16NJz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_GYkZQBmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.gYkZQBm' shared service.
     *
     * @return \App\Entity\ItemRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\ItemController::index()": the $itemRepository argument is type-hinted with the non-existent class or interface: "App\\Entity\\ItemRepository".');
    }
}
