<?php

namespace Container2v16NJz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KlVCS6jService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.klVCS6j' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.klVCS6j'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'itemRepository' => ['privates', '.errored.gYkZQBm', NULL, 'Cannot determine controller argument for "App\\Controller\\ItemController::index()": the $itemRepository argument is type-hinted with the non-existent class or interface: "App\\Entity\\ItemRepository".'],
        ], [
            'itemRepository' => '?',
        ]);
    }
}
