<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH7Z1CLj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH7Z1CLj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH7Z1CLj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH7Z1CLj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH7Z1CLj\App_KernelDevDebugContainer([
    'container.build_hash' => 'H7Z1CLj',
    'container.build_id' => '521ab969',
    'container.build_time' => 1612362806,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH7Z1CLj');
