<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPig7lcS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPig7lcS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPig7lcS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPig7lcS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPig7lcS\App_KernelDevDebugContainer([
    'container.build_hash' => 'Pig7lcS',
    'container.build_id' => 'e16aed98',
    'container.build_time' => 1611056557,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPig7lcS');
