<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVW00VMu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVW00VMu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVW00VMu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVW00VMu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVW00VMu\App_KernelDevDebugContainer([
    'container.build_hash' => 'VW00VMu',
    'container.build_id' => '7cd89649',
    'container.build_time' => 1609178296,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVW00VMu');
