<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'item_index' => [[], ['_controller' => 'App\\Controller\\ItemController::index'], [], [['text', '/api/items/']], [], []],
    'item_new' => [[], ['_controller' => 'App\\Controller\\ItemController::store'], [], [['text', '/api/items/store']], [], []],
    'item_show' => [['id'], ['_controller' => 'App\\Controller\\ItemController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/items']], [], []],
    'item_edit' => [['id'], ['_controller' => 'App\\Controller\\ItemController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/items']], [], []],
    'item_delete' => [['id'], ['_controller' => 'App\\Controller\\ItemController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/items']], [], []],
    'Todolist_index' => [[], ['_controller' => 'App\\Controller\\TodolistController::index'], [], [['text', '/api/todolists/']], [], []],
    'Todolist_new' => [[], ['_controller' => 'App\\Controller\\TodolistController::store'], [], [['text', '/api/todolists/store']], [], []],
    'Todolist_show' => [['id'], ['_controller' => 'App\\Controller\\TodolistController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/todolists']], [], []],
    'Todolist_edit' => [['id'], ['_controller' => 'App\\Controller\\TodolistController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/todolists']], [], []],
    'Todolist_delete' => [['id'], ['_controller' => 'App\\Controller\\TodolistController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/todolists']], [], []],
    'user_index' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/api/users/']], [], []],
    'user_store' => [[], ['_controller' => 'App\\Controller\\UserController::store'], [], [['text', '/api/users/store']], [], []],
    'user_show' => [['id'], ['_controller' => 'App\\Controller\\UserController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/users']], [], []],
    'user_edit' => [['id'], ['_controller' => 'App\\Controller\\UserController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/users']], [], []],
    'user_delete' => [['id'], ['_controller' => 'App\\Controller\\UserController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/users']], [], []],
];
